apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: test-nginx
  name: test-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      run: test-nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: test-nginx
    spec:
      containers:
      - image: nginx
        name: test-nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
