apiVersion: v1
kind: Namespace
metadata:
  name: team-a

---

apiVersion: v1
kind: LimitRange
metadata:
  namespace: team-a
  name: teama-limit-range
spec:
  limits:
    - default:
        memory: 200Mi
        cpu: 300m
      defaultRequest:
        memory: 100Mi
        cpu: 150m
      type: Container

    - max:
        cpu: 400m
        memory: 700Mi
      min:
        cpu: 300m
        memory: 500Mi
      type: Pod
