apiVersion: v1
kind: Namespace
metadata:
  name: qa
---
apiVersion: v1
kind: ResourceQuota
metadata:
  namespace: qa
  name: dev-ns-resourcequota
spec:
  hard:
    pods: "1"
    configmaps: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: qa
  name: nginx-deploy
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      team: qa
    template:
      metadata:
        app: nginx
        team: qa
      spec:
        containers:
          - image: nginx
            name: nginx
