apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
---
apiVersion: v1
kind: LimitRange
metadata:
  namespace: dev
  name: dev-limit-range
spec:
  limits:
    - default:
        cpu: 50m
        memory: 100Mi
      defaultRequest:
        cpu:

---
apiVersion: v1
kind: ResourceQuota
metadata:
  namespace: dev
  name: dev-cpu-mem-quota
spec:
  hard:
    limits.memory: 1Gi
    limits.cpu: 500m
---
apiVersion: v1
kind: ResourceQuota
metadata:
  namespace: prod
  name: prod-cpu-mem-quota
spec:
  hard:
    limits.memory: 1Gi
    limits.cpu: 400m

