apiVersion: v1
kind: Pod
metadata:
  name: busybox-test
  labels:
    app: busybox
spec:
  containers:
    - image: busybox
      name: busybox-container
      command: ['/bin/sh','-c']
      args:
        - sleep 1000
