apiVersion: v1
kind: Pod
metadata:
  name: centos-privileged
  labels:
    app: centos
    tier: frontend
spec:
  containers:
    - image: centos
      name: centos-container
      stdin: true
      tty: true
      securityContext:
        privileged: true
