apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-nobody
  labels:
    app: ubuntu
spec:
  securityContext:
    runAsUser: nobody
    fsGroup: nobody
  containers:
    - image: ubuntu
      name: ubuntu-container
      stdin: true
      tty: true
