apiVersion: v1
kind: Pod
metadata:
  namespace: test
  name: pod-test
  labels:
    app: centos
    env: test
spec:
  containers:
    - image: centos
      name: centos-container
      tty: true
      stdin: true

